### Question 1

In [2]:
import numpy as np 

In [2]:
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

### Question 2

In [14]:
l = []
m = []
for i in range(5):
    i = input()
    l.append(i)
print(l) 

for j in range(5):
    j = input()
    m.append(j)
print(m)

con = np.concatenate([l, m],axis=0)
print(con)

np.sort(con)

1
2
3
4
5
['1', '2', '3', '4', '5']
6
7
8
9
10
['6', '7', '8', '9', '10']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


array(['1', '10', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U2')

### Question 3 

In [19]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]])
print(arr.ndim)
print(arr.size)

2
6


### Question 4

In [8]:
arr = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr)

arr2 = arr.reshape(2, 5)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Question 5

In [17]:
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]]) 
  
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


### Question 6

In [23]:
list1 = [1,2,3,4,5,6,3,4,2]
print(np.unique(list1))
print(len(np.unique(list1)))

[1 2 3 4 5 6]
6
